In [2]:
# HOW TO CREATE A MATRIX IN NUMPY

import numpy as np
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [6,10,11,12]
])
print(A.shape) #3 row and 4 col
print(A.ndim) # dimension
print(A.size) # total elements
print(A.dtype)

(3, 4)
2
12
int32


In [4]:
#slicing element: A[row, col]
print(A[0,0]) #top left corner of first number
print(A[1,2]) #row 1 col 2
print(A[-1, -1]) # bottom left corner

#SILICING AN entire row
print(A[1, :])
print(A[1])

1
7
12
[5 6 7 8]
[5 6 7 8]


## CREATING MATRICES

In [8]:
# ones
# zeors

import numpy as np
o=np.ones((3,4))
z=np.zeros((3,3))
print(o)
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# identity matrix
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# to create random numbers
r = np.random.rand(3,3) # generates numbers btw 0 and 1
print(r)

[[0.24230439 0.54390024 0.60511284]
 [0.44331853 0.41334079 0.61938936]
 [0.47671735 0.3367365  0.3420007 ]]


In [15]:
n = np.random.rand(3,3) # standard normal with min 0
print(n)

[[0.26683736 0.43666614 0.80006158]
 [0.26671178 0.35694999 0.45770798]
 [0.74289159 0.66054605 0.27062538]]


In [47]:
import numpy as np
import matplotlib.pyplot as plt
m=np.random.rand(5, 5)
plt.figure(figsize=(6,5))
#cmar= np.random.rand(3, 3) # generates number btw 0 and 1
#plt.imshow(m, cmar)
#print(r)p='Blues'
#plt.colorbar()
#plt.title('Matrix as a Heatmap')
plt.imshow(m cmap='Blues')  #'cmap' sets the color scheme
plt.colorbar()              # show the color scale
plt.title('Matrix as a Heatmap')


# Annotate each cell with its value
for i in range(5):
    for j in range(5):
        plt.text(j, i, f'{m[i,j]:.2f}',
                ha='center', va='center', fontsize=9)
plt.show()        

SyntaxError: invalid syntax (3972599760.py, line 10)

In [27]:
A=np.array([[1,2,3],
           [4,5,6]]) # shape (2, 3)
B=np.array([[7, 8],
           [9, 10],
           [11, 12]]) # shape (3, 2)
C=A@B # matrix multiply 
print(C)
# or 
# c=np.dot(a,b)

[[ 58  64]
 [139 154]]


In [28]:
# TRANSPOSE OF A MATRIX
# FLIPS A MATRIX OVER ITS DIAGONAL, ROW BECOMECOLUMN BECOMESROWS

In [30]:
A=np.array([[1,2,3,4],
            [5,6,7,8]
])
print(A.shape)

(2, 4)
